"""add pin to user table

Revision ID: 05876a702a0e
Revises: ae56bc54ef39
Create Date: 2026-07-20 14:45:39.247087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05876a702a0e'
down_revision: Union[str, Sequence[str], None] = 'ae56bc54ef39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin_hash')
    # ### end Alembic commands ###
