"""remove source of fund from user

Revision ID: 1fb2bee124d2
Revises: f368d7fc1fc0
Create Date: 2026-07-28 09:59:36.504339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb2bee124d2'
down_revision: Union[str, Sequence[str], None] = 'f368d7fc1fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('senders', 'sender_source_of_fund')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senders', sa.Column('sender_source_of_fund', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
