"""add users table

Revision ID: ae56bc54ef39
Revises: 
Create Date: 2026-07-20 12:42:38.483011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae56bc54ef39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sender_customer_type', sa.String(length=1), nullable=False),
    sa.Column('sender_first_name', sa.String(length=100), nullable=True),
    sa.Column('sender_middle_name', sa.String(length=100), nullable=True),
    sa.Column('sender_last_name', sa.String(length=100), nullable=True),
    sa.Column('sender_company_name', sa.String(length=255), nullable=True),
    sa.Column('sender_company_reg_number', sa.String(length=100), nullable=True),
    sa.Column('sender_company_incorporate_date', sa.Date(), nullable=True),
    sa.Column('sender_gender', sa.String(length=1), nullable=True),
    sa.Column('sender_native_first_name', sa.String(length=150), nullable=True),
    sa.Column('sender_native_last_name', sa.String(length=150), nullable=True),
    sa.Column('sender_address', sa.String(length=255), nullable=True),
    sa.Column('sender_city', sa.String(length=100), nullable=True),
    sa.Column('sender_state', sa.String(length=100), nullable=True),
    sa.Column('sender_zip_code', sa.String(length=20), nullable=True),
    sa.Column('sender_country', sa.String(length=3), nullable=False),
    sa.Column('sender_mobile', sa.String(length=30), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('sender_nationality', sa.String(length=3), nullable=True),
    sa.Column('sender_id_type', sa.String(length=50), nullable=False),
    sa.Column('sender_id_number', sa.String(length=100), nullable=False),
    sa.Column('sender_id_issue_country', sa.String(length=3), nullable=True),
    sa.Column('sender_id_issue_date', sa.Date(), nullable=True),
    sa.Column('sender_id_expire_date', sa.Date(), nullable=True),
    sa.Column('sender_date_of_birth', sa.Date(), nullable=True),
    sa.Column('sender_secondary_id_type', sa.String(length=50), nullable=True),
    sa.Column('sender_secondary_id_number', sa.String(length=100), nullable=True),
    sa.Column('sender_occupation', sa.String(length=100), nullable=True),
    sa.Column('sender_source_of_fund', sa.String(length=100), nullable=True),
    sa.Column('sender_beneficiary_relationship', sa.String(length=10), nullable=False),
    sa.Column('purpose_of_remittance', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('senders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
