"""add remove benefeciary relationship and purpose of remittance

Revision ID: f368d7fc1fc0
Revises: efc8538b8921
Create Date: 2026-07-23 14:22:14.648558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f368d7fc1fc0'
down_revision: Union[str, Sequence[str], None] = 'efc8538b8921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('senders', 'purpose_of_remittance')
    op.drop_column('senders', 'sender_beneficiary_relationship')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senders', sa.Column('sender_beneficiary_relationship', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('senders', sa.Column('purpose_of_remittance', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
